version: '3.9'

services:
  # Frontend service
  thesis-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thesis-frontend
    ports:
      - "3000:5000"  # Host port 3000 mapped to container port 5000
    environment:
      - NODE_ENV=production
    restart: always

  # # Backend service
  # openvidu-backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: openvidu-backend
  #   ports:
  #     - "6080:6080"  # Host port 8080 mapped to container port 6080
  #   environment:
  #     - NODE_ENV=production
  #   restart: always